sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=full
- push-type=branch
- build-pattern=snrinf.tex
- packages=lipsum, blindtext, framed
env:
  global:
  - IS_TRAVIS=true
  - secure: wt3JWblU/bU35R00BJGoWRyzekMfXymQyR7tq9dz2pM5xhLArhP05Zla2fqRLfukgIl317Dh51Idxwgj313sDzyEzf1VOCMAkznG7DeWcq67ZBrTDpMYTCJO5SUtb0HN6ERIS1nlLcU3n9juRu3gdsJBKPpGVrbCQ9xbR/B1EO+gWipcK8taRTnAYO5blrUIrHlfzvNUSmpy5aokWfmAqXwuaQOlGnIiK5EsYAnSj+q7PrWCAAEWHpUzCufynwDCIRF4ocH3TKp7MkPS9VnmaAXzh42Y5LoGxJTPc47MQXxpAL6P8ErPw4n0RpZA6PLbI46BQD2jyNPuCuFysDMxaBlYEXy/D8pot6cni1MrZrrLS9gwXbLDp/SFGOewo2pApVS7XTNkDoaXz/y4negXazsOk3fWV+yjeHGetw+24O/KosnGvoXa03ewKtcFGr5yjvZyFhR4mj2thAH7Btt0APf9txlCrOtH2fNwYfM7bW+ZtLvyxfDyFTms4rV20exv9eP58NdWo72RbDerA4e/vi8mc7HkLANLAF6d9naaUF4dXeKR1XWG9GZwGYWWVw/gEtilWMk/GQgBSbD6smWpLOzZ3It/6jsPsQ2MuwdiZ/r96LdlKVeFjoteQeVjN4Eqa3gm4lyiHlMcauXun2tg8u7sDFhCIyvMCQ6oAk+inWc=
script:
- chmod +x .travis/travis-texbuild.sh
- ".travis/travis-texbuild.sh"
